##########################################
#  The HUGO Book, by Kent Tessman 2004:  #
#  https://github.com/tajmone/hugo-book  #
##########################################

dist: trusty

git:
  depth: false

install:
  - npm install -g eclint
  # - gem install asciidoctor

script:
  - eclint check
