[colophon]
= Colophon

The Hugo Book +
Hugo: An Interactive Fiction Design System

Copyright (C) 2004 by Kent Tessman +
The General Coffee Company Film Productions +
www.generalcoffee.com

All rights reserved.
No part of this book may be used or reproduced in any form or by any means, or stored in a database or retrieval system, without prior written permission of the publisher except in the case of brief quotations embodied in critical articles and reviews.

*Warning and Disclaimer*

This book is sold as is, without warranty of any kind, either express or implied.
While every precaution has been taken in the preparation of this book, neither the author nor the publisher assumes any responsibility for errors or omissions.
Neither is any liability assumed for damages resulting from the use of the information or instructions contained herein.
It is further stated that neither the author nor the publisher is responsible for any damage or loss to any data or equipment that results directly or indirectly from the use of this book.

_First Edition_

_ISBN 0-9735652-0-9_

// EOF //
